sudo: required

services:
  - docker

dist: trusty

language: node_js

node_js: '8'

cache: yarn

script:
  - mvn clean package -U
  - docker build -t $DOCKER_USERNAME/twitterstreamservice .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/twitterstreamservice
